### ISSUE TITLE
Feature request: (Option to) disable rogue android death messages.

### ISSUE THREAD

**Issue by Ionaru** [Ionaru/MatterMegadrive#4]
Every time a rogue android is killed, a death message appears in chat. I'd like to have an option to disable this behaviour.

**Comment by BlueAngel87** [comment]
I would like it to be an option. in the end its a bit annoying being spamed with it in the chat. could be awesome too could be able to disable it :)

**Comment by Ionaru** [comment]
Added as an option called `android_names`, setting this option to `false` will stop giving names to Rogue Androids and this will also prevent the death messages from appearing.

This only applies to newly spawned Rogue Androids, those that already exist in the world will still have their names and death messages.

**Comment by BlueAngel87** [comment]
awesome :D
