### ISSUE TITLE
enchantment id conflict

### ISSUE THREAD

**Issue by ghost** [Ionaru/MatterMegadrive#9]
**Brief explanation of the problem**

a duplicate enchantment id 

**Steps to reproduce**

add witching gadgets version and it depences 
https://minecraft.curseforge.com/projects/witching-gadgets/files/2262119

and download this version of matter mega drive
https://minecraft.curseforge.com/projects/matter-megadrive/files/2514503  

**Crash report **
https://github.com/BluSunrize/WitchingGadgets/issues/126

[crash-2019-03-12_12.25.35-client.txt](https://github.com/Ionaru/MatterMegadrive/files/2958522/crash-2019-03-12_12.25.35-client.txt)

**Matter Megadrive version** 
https://minecraft.curseforge.com/projects/matter-megadrive/files/2514503

currently getting help from this mod creator
https://github.com/fewizz/NotEnoughIDs/issues/87

**Comment by ghost** [comment]
hi its me crae i would like some fix in the near future it would help a lot

**Comment by ghost** [comment]
sorry the enchantment id is not going to be fixed because it is going to be updated

**Comment by ghost** [comment]
found a fix its enchantment id 100 closing the issue

**Comment by Ionaru** [comment]
Nice that you found a solution!

A tip: NEI can export lists of IDs that might help with finding an unused ID to resolve conflicts.
